pipeline {
    agent { label 'AGENT-1' }

    environment {
        PROJECT = 'EXPENSE'
        COMPONENT = 'BACKEND'
        DEPLOY_TO = 'production'
    }

    options { 
        disableConcurrentBuilds() 
        timeout(time: 30, unit: 'MINUTES')
        ansiColor('Xterm')
    }
    parameters{
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')
    }
    stages {
        stage('Init') {
            steps {
                script{
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                            cd 00-VPC
                            terraform init -reconfigure
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('Apply') {
            input {
                message "should we continue?"
                ok "yes, we should."
            }
            steps {
                script{
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                            cd 00-VPC
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        stage('Trigger SG'){
            when { 
                expression { params.ACTION == 'apply'}
            }
            steps{
                build job: '10-SG', parameters: [string(name: 'ACTION', value: 'apply')], 
                propagate: true
            }
        } 
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        failure { 
            echo 'I will run when pipeline is failed'
        }
        success { 
            echo 'I will run when pipeline is success'
        }
    }
}



// pipeline {
//     agent { label 'AGENT-1' }
//     stages {
//         stage('Build') {
//             steps {
//                  script{
//                  sh """
//                     echo "Hello, this is build"
//                  """
//                 }
//             }
//         }
//         stage('Test') {
//             steps {
//                 script{
//                  sh """
//                     echo "Hello, this is test"
//                  """
//                 }
//             }
//         }
//         stage('Deploy') {
//             steps {
//                 script{
//                  sh """
//                     echo "Hello, this is Deploy"
//                  """
//                 }
//             }
//         }
//     }
//     post { 
//         always { 
//             echo 'I will always say Hello again!'
           
//         }
//         failure { 
//             echo 'I will run when pipeline is failed'
//         }
//         success { 
//             echo 'I will run when pipeline is success'
//         }
//     }        
// }